services:
  - type: web
    name: venifretes-backend
    runtime: java
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: MAVEN_OPTS
        value: -Xmx512m
      - key: JAVA_OPTS
        value: -Xmx512m
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        sync: false
    healthCheckPath: /actuator/health
